---
label: &label Spelling Bee Assistant
url: &url https://draber.github.io/
twitter: "@d_raber"
ga:
  tid: UA-182372232-1
  ec: SBA Download
container:
  text: Assistant
  attributes:
  	draggable: true
    title: Hold the mouse down to drag assistant
  classNames:
    - dragger
  closer:
    title: Close assistant
    text: ×
  panels:
    - tag: &panel details
      text: Stats
      open: true
    - tag: *panel
      text: Spoilers
    - tag: *panel
      text: Solution
  footer:
    tag: a
    text: 
      - *label 
      - "{{config.version}}"
    attributes:
      href: *url
      target: _blank